#include "Chuck.h";
#include "w-walk.h";
#include "w-swim.h";
#include "tree.h";
#include "water.h";
#include "fruits.h";
#include "meats.h";
#include "cashier.h";
#include "breads.h";
#include "st-door.h";
#include "st-aisle.h";

typedef struct {
    Chuck Chuck;
    WomenWalking WomenWalking[5];
    WomenSwimming WomenSwimming[3];
    Tree Tree[10];
    Water Water;
    Meats Meats;
    Breads Breads;
    Fruits Fruits;
    Cashier Cashier;
    StoreDoor StoreDoor;
    StoreAisle StoreAisle[3];
    Timer Timer;
    Vampire Vampire;
    Bats Bats[3];
    Puddle Puddle;
} Model;