# Variables for Compilers and Flags
CC  = cc68x
ASM = gen
GLD = gen -L2 -D

# List of all Object Files needed for the final game
OBJS = chuck.o asynch.o cisr.o cisr_asm.o cond.o effects.o font.o \
       game.o input.o model.o psg.o raster.o rast_asm.o \
       renderer.o sound.o start.o synch.o

# link everything into the chuck.tos executable
chuck.tos: $(OBJS)
	$(CC) -g $(OBJS) -o chuck.tos


asynch.o: asynch.c asynch.h
	$(CC) -g -c asynch.c

chuck.o: chuck.c
	$(CC) -g -c chuck.c

cisr.o: cisr.c cisr.h
	$(CC) -g -c cisr.c

cond.o: cond.c cond.h
	$(CC) -g -c cond.c

effects.o: effects.c effects.h
	$(CC) -g -c effects.c

font.o: font.c font.h
	$(CC) -g -c font.c

game.o: game.c game.h
	$(CC) -g -c game.c

input.o: input.c input.h
	$(CC) -g -c input.c

model.o: model.c model.h
	$(CC) -g -c model.c

psg.o: psg.c psg.h
	$(CC) -g -c psg.c

raster.o: raster.c raster.h
	$(CC) -g -c raster.c

renderer.o: renderer.h renderer.c
	$(CC) -g -c renderer.c

sound.o: sound.h sound.c
	$(CC) -g -c sound.c

start.o: start.h start.c
	$(CC) -g -c start.c

synch.o: synch.h synch.c
	$(CC) -g -c synch.c

# This handles your assembly VBL wrapper
cisr_asm.o: cisr_asm.s
	$(GLD) cisr_asm.s

rast_asm.o: rast_asm.s
	$(GLD) rast_asm.s