#include <osbind.h>
#include "raster.h"
#include "Chuck.h"

/* @author Gaurik */
int main()
{

	/* bitmaps generated by Google Gemini for testing purposes 
	PROMPT: "Generate a 8x8 cross, 16x16 batman logo and 32x32 darth vader bitmaps"*/
	/* 8x8 Bitmap - 1 byte per row */
	static const UINT8 cross_8x8[] = {
    	0x18, /* 00011000   */
    	0x18, /* 00011000   */
    	0x7E, /* 01111110   */
    	0x7E, /* 01111110   */
    	0x18, /* 00011000   */
    	0x18, /* 00011000   */
    	0x18, /* 00011000   */
    	0x18  /* 00011000   */
	};
	
	/* 16x16 Bitmap - 1 unsigned short (16-bit) per row */
	static const UINT16 batman_16x16[] = {
    	0x0000, /* 0000000000000000 */
    	0x6006, /* 0110000000000110 */
    	0xF00F, /* 1111000000001111 */
    	0xFDDF, /* 1111110110111111 */
    	0xFFFF, /* 1111111111111111 */
    	0xFFFF, /* 1111111111111111 */
    	0xFFFF, /* 1111111111111111 */
    	0x7FFE, /* 0111111111111110 */
    	0x3FFC, /* 0011111111111100 */
    	0x1FF8, /* 0001111111111000 */
    	0x0FF0, /* 0000111111110000 */
    	0x07E0, /* 0000011111100000 */
    	0x03C0, /* 0000001111000000 */
    	0x0180, /* 0000000110000000 */
    	0x0000, /* 0000000000000000 */
    	0x0000  /* 0000000000000000 */
	};

	/* 32x32 Bitmap - 1 unsigned long (32-bit) per row */
	static const UINT32 vader_32x32[] = {
    	0x00000000, 0x000FC000, 0x003FF000, 0x007FF800,
    	0x00FFF800, 0x01FFF800, 0x03FFF800, 0x07FFF800,
    	0x0FFFFC00, 0x1FFFFE00, 0x3FFFFF00, 0x7FFFFF80,
    	0xFFFFFC00, 0xFFFFFC00, 0xFF999C00, 0xFF111C00,
    	0xFE000C00, 0xFC000600, 0xF83C0300, 0xF87E0300,
    	0xF07E0100, 0xE0FF0000, 0xC1FF8000, 0x83FFC000,
    	0x07FFE000, 0x0FFFF000, 0x1FFFF800, 0x3FFFFC00,
    	0x7FFFFE00, 0xFFFFFFFF, 0xFFFFFFFF, 0x00000000
	};

	void *base = Physbase();
	clear_screen(base);
	plot_pixel(base, 100, 100);
	plot_horizontal_line(base, 10, 10, 10);
	plot_vertical_line(base, 15, 15, 10);
	plot_line(base, 20, 20, 30, 30);
	plot_rectangle(base, 35, 35, 10, 40);
	plot_square(base, 35, 10, 10);
	
	plot_triangle(base, 150, 200, 10, 10, 0);
	plot_triangle(base, 150, 220, 10, 10, 1);
	plot_triangle(base, 150, 240, 10, 10, 2);
	plot_triangle(base, 150, 260, 10, 10, 3);
	
	plot_8_bitmap(base, 200, 200, 8, cross_8x8);
	plot_16_bitmap(base, 200, 250, 16, batman_16x16);
	plot_32_bitmap(base, 200, 300, 32, vader_32x32);
	
	plot_character(base, 350, 200, 'A');
	plot_string(base, 350, 210, "Hello there.");
	
	return 0;
}